name: iOS pod CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Get Pod Version
      run: |
        rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "curr_tag=$rtt" >> $GITHUB_ENV
        
#faac-v2.2.2
#ijkplayer-v2.2.2
#soundtouch-v0.0.1
#tpns-v2.2.2
#wechat-v2.2.2
#xp2p-v2.2.2
#xp2p-v2.2.2-beta.1

    - name: Deploy faac SDK
      if: ${{contains(env.curr_tag, 'faac')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_Faac.podspec
                
        pod lib lint TIoTLinkKit_Faac.podspec --verbose --allow-warnings --use-libraries
        pod trunk push TIoTLinkKit_Faac.podspec --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
    
    
    
    - name: Deploy ijkplayer SDK
      if: ${{contains(env.curr_tag, 'ijkplayer')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_IJKPlayer.podspec
                
        pod lib lint TIoTLinkKit_IJKPlayer.podspec --verbose --allow-warnings --use-libraries
        pod trunk push TIoTLinkKit_IJKPlayer.podspec --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}


    - name: Deploy tpns SDK
      if: ${{contains(env.curr_tag, 'tpns')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_TPNS.podspec
                
        pod lib lint TIoTLinkKit_TPNS.podspec --verbose --allow-warnings --use-libraries
        pod trunk push TIoTLinkKit_TPNS.podspec --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
        
        
    - name: Deploy wechat SDK
      if: ${{contains(env.curr_tag, 'wechat')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_WechatOpenSDK.podspec
                
        pod lib lint TIoTLinkKit_WechatOpenSDK.podspec --verbose --allow-warnings --use-libraries
        pod trunk push TIoTLinkKit_WechatOpenSDK.podspec --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
        
        
    - name: Deploy xp2p SDK
      if: ${{contains(env.curr_tag, 'xp2p')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_XP2P.podspec
                
        pod lib lint TIoTLinkKit_XP2P.podspec --verbose --allow-warnings --use-libraries
        pod trunk push TIoTLinkKit_XP2P.podspec --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}

  
    - name: Deploy flv SDK
      if: ${{contains(env.curr_tag, 'flv')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_FLV.podspec
                
        pod lib lint TIoTLinkKit_FLV.podspec --verbose --allow-warnings --use-libraries
        pod trunk push TIoTLinkKit_FLV.podspec --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
    
  
    - name: Deploy soundtouch SDK
      if: ${{contains(env.curr_tag, 'soundtouch')}}
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        vtaglist=(${temptag//-/ })
        beta=${vtaglist[2]}
        version=${vtaglist[1]}
        if [ ${#beta} -gt 0 ]
        then
            version=${vtaglist[1]}-$beta
        fi
        version=${version#*v}
        echo $version

        export LIB_VERSION=$version
        perl -i -pe "s#.*s.source .*#\ts.source           = { :git => 'https://github.com/tencentyun/iot-thirdparty-ios.git', :tag => \"$temptag\" }#g" TIoTLinkKit_SoundTouch.podspec
                
        pod lib lint TIoTLinkKit_SoundTouch.podspec --verbose --allow-warnings --skip-import-validation
        pod trunk push TIoTLinkKit_SoundTouch.podspec --verbose --allow-warnings --skip-import-validation
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
